### ISSUE TITLE
Organize fails with an unhelpful error when attempting to overwrite a file

### ISSUE THREAD

**Issue by bepri** [canonical/craft-parts#1007]
### Bug Description

If an `organize:` key attempts to use fileglobs to merge two files, this rather silly error is made:
```
❯ snapcraft pack
None
Detailed information: Error
```

### To Reproduce

Attempt to use a fileglob to organize a directory that already partially exists.

### part yaml

```shell
parts:
  foo:
    plugin: nil
    organize:
      # This globbing is important for the bug, it seems
      "**/foo-lib/*": foo-lib
    override-build: |
      # Make a directory and a clone of it in $CRAFT_PART_INSTALL
      mkdir foo-lib
      mkdir $CRAFT_PART_INSTALL/foo-lib

      # Populate the local version
      touch foo-lib/bar
      touch foo-lib/baz

      # Only partially copy the destination
      touch $CRAFT_PART_INSTALL/foo-lib/bar
```

### Relevant log output

```shell
❯ snapcraft pack
None
Detailed information: Error
Failed to execute snapcraft in instance.
```

**Comment by upils** [comment]
Simplified reproducer:

```
parts:
  foo:
    plugin: nil
    organize:
      "foo-lib/*": foo-lib/
    override-build: |
      mkdir $CRAFT_PART_INSTALL/foo-lib
      touch $CRAFT_PART_INSTALL/foo-lib/bar
```
