### ISSUE TITLE
Can't download an uncompressed binary

### ISSUE THREAD

**Issue by knkski** [canonical/craft-parts#136]
Similar to https://bugs.launchpad.net/snapcraft/+bug/1839842.

My use case is that I'd like to download a binary like https://dl.k8s.io/release/v1.22.1/bin/linux/amd64/kubectl

That doesn't currently work from what I can see, and requires a workaround similar to the snapcraft bug:

```yaml
parts:
  kubectl:
    plugin: dump
    source: .
    override-pull: |
      curl -sSLO https://dl.k8s.io/release/v1.22.1/bin/linux/amd64/kubectl
      chmod +x kubectl
    build-packages:
      - curl
```
