### ISSUE TITLE
Include all partitions by default for `stage` and `prime` keywords

### ISSUE THREAD

**Issue by mr-cal** [canonical/craft-parts#650]
### What needs to get done

When the ‘stage’ and ‘prime’ keywords are not provided for a part, craft-parts’ default behavior should be to stage and prime all files for the part in all partitions.

If a stage or prime filter is defined for a partition, the default behavior will not be affected for the other partitions.

Using the partitions (‘default’, ‘foo’, and ‘bar), consider the following examples.

#### Exclusion example
The ‘default’ and ‘bar’ partitions will follow the default behavior - all contents in these partitions will be staged.
Everything in the ‘foo’ partition is staged except for ‘a/c’.  
```yaml
parts:
  my-part:
    organize:
      a: (foo)/a
      b: (bar)/b
    stage:
      - -(foo)/a/c
```

#### Inclusion example
The ‘default’ and ‘bar’ partitions will follow the default behavior - all contents in these partitions will be staged.
Everything in the ‘foo’ partition, only the ‘a/c’ file is staged.  
```yaml
parts:
  my-part:
    organize:
      a: (foo)/a
      b: (bar)/b
    stage:
      - (foo)/a/c
```

### Why it needs to get done

To align with the spec.

* The current implementation in `main` applies `*` to all partitions.
* The current implementation in `feature/namespaced-partitions` applies `*` to only the default partition, so a user has to explicitly stage and prime their partitions, which is burdensome and overly verbose:
```yaml
parts:
  foo:
    plugin: dump
    source: .
    organize: 
      (default)/file: (mypart)/file
    stage:
     - (default)/*
     - (mypart)/*
    prime:
     - (default)/*
     - (mypart)/*
```
