### ISSUE TITLE
`python-extras` keyword for Python plugin

### ISSUE THREAD

**Issue by lengau** [canonical/craft-parts#657]
### What needs to get done

It would be nice to have a `python-extras` keyword for the python plugin that will install the given package with any extras specified.

Example:

```
parts:
  codespell:
    plugin: python
    source: https://github.com/codespell-project/codespell
    source-type: git
    source-tag: v2.2.6
    source-depth: 1
	python-extras:
		- toml
```

would [at the appropriate place](https://github.com/canonical/craft-parts/blob/bd6c687f30dc72346816d7cd0b4ceabc8e530d92/craft_parts/plugins/python_plugin.py#L115) run

`pip install -U .[toml]`

### Why it needs to get done

Quality of life improvement
