### ISSUE TITLE
Jlink support for Java plugin

### ISSUE THREAD

**Issue by vpa1977** [canonical/craft-parts#891]
### What needs to get done

Java plugin should set JAVA_HOME https://github.com/canonical/craft-parts/issues/891 and provide a way to generate runtime for the Java application.

This can be done by running `jlink` and passing a list of jar files. Java plugin by default copies files to `$CRAFT_PART_INSTALL/jars` and java plugin will pick up jars from this location in post build commands and generate the runtime for those jars. User should be able to specify the version of the Java to use and list of jar files and directories if the default value is not acceptable. User should be able to specify if he wants to run a jlink step.
Java should be available as a plugin so that build without applying derivative plugins is supported.

- register Java as a plugin.
```
parts:
   foo:
     plugin: java
     jlink: true
     jlink_java_version: 21
     jlink_jars:
        - $CRAFT_PART_INSTALL/jar/jar1.jar
        - $CRAFT_PART_BUILD/jar/jar2.jar
```  
- The plugin should install chisel slices into a build root (otherwise it affects build JDK)
- The plugin should use chiselled runtime to generate jlink runtime. 

### Why it needs to get done

To have a lean runtime for java applications
