### ISSUE TITLE
Add an option to use `uv venv` and `uv pip` in the `python` and `poetry` plugins

### ISSUE THREAD

**Issue by lengau** [canonical/craft-parts#936]
### What needs to get done

This old experimental PR is an example: https://github.com/canonical/craft-parts/pull/825

You should be able to make parts like:

```yaml
parts:
  python:
    source: .
    python-package-manager: uv
  poetry:
    source: .
    poetry-package-manager: uv
```

and instead of using the system `python -m venv` and installing pip in that virtual environment, it would use uv for the relevant `venv` and `pip` commands.

### Why it needs to get done

The old methods are both slow and can be error-prone since the behaviour of `venv` and `pip` changes from base to base.
